inherit_from: .rubocop_todo.yml

# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
Layout/IndentationWidth:
  Width: 2 # Common choices are 2 or 4 spaces.

# Enforce consistent indentation for internal methods and blocks.
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods # Ensures internal methods are indented relative to the outer scope.

# Specify whether to use spaces or tabs for indentation.
Layout/IndentationStyle:
  EnforcedStyle: spaces # Use 'spaces' or 'tabs' depending on your preference.