default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: <%= ENV['TENANT_DATABASE_DEV'] %>
  username: <%= ENV['TENANT_DATABASE_USER_DEV'] %>
  password: <%= ENV['TENANT_DATABASE_PASSWORD_DEV'] %>

test:
  <<: *default
  database: tenant_management_system_test


production:
  <<: *default
  database: <%= ENV['TENANT_DATABASE_PROD'] %>
  username: <%= ENV['TENANT_DATABASE_USER_PROD'] %>
  password: <%= ENV['TENANT_DATABASE_PASSWORD_PROD'] %>